### ISSUE TITLE
Miscellaneous TODOs left over

### ISSUE THREAD

**Issue by demiurgeQuantified** [demiurgeQuantified/PZEventDoc#3]
There's a few events that I couldn't work out the exact trigger circumstances for:
* [x] OnGetDBSchema
* [x] OnGetTableResult
* [x] OnReceiveUserlog
* [x] onUpdateIcon

Additionally, these events have some unclear parameters:
* [ ] OnMouseMove
* [ ] OnServerWorkshopItems

If somebody could take a look at any of these, it'd be greatly appreciated!

**Comment by omarkmu** [comment]
The difference between the coordinates in `OnMouseMove` is that parameters 3 and 4 are x and y (respectively) multiplied by player 1's zoom factor (e.g., 2.5 for 250% zoom). Also, oddly enough, the event does not only fire when the mouse moves. It's triggered on every frame unless the event is consumed by another mouse move callback.

As for the "progress" type of `OnServerWorkshopItems`, parameter 3 is the bytes already downloaded and parameter 4 is the total bytes that need to be downloaded. They should be measured in bytes based on [this](https://partner.steamgames.com/doc/api/ISteamUGC#GetItemDownloadInfo), anyway; I haven't tested that myself to confirm, but I think I remember seeing values large enough to be bytes in log files in the past.
